### ISSUE TITLE
Type script import error

### ISSUE THREAD

**Issue by trueflywood** [lmcarreiro/smart-column-indenter#8]
code:

```
import { Component, OnInit } from '@angular/core';
import { DataServiceService } from 'src/app/services/data-service.service';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { faChevronLeft } from '@fortawesome/free-solid-svg-icons';
```

before:

![image](https://user-images.githubusercontent.com/13107413/78239564-84f26680-74e6-11ea-9cdb-04dc2440c622.png)

after: 

![image](https://user-images.githubusercontent.com/13107413/78239666-ab180680-74e6-11ea-8ef9-e1444818b20a.png)

**Comment by lmcarreiro** [comment]
It only works with monospaced (fixed-width) fonts.
